### ISSUE TITLE
wp_config_constants get html encoded which causes weird results

### ISSUE THREAD

**Issue by kodie** [itsahappymedium/wp-deployer#8]
For example, if I have this in my config.yml file:

```yml
wp_config_constants:
  <<: *default_wp_config_constants
  WP_MAIL_FROM: Person & Person Company
```

it'll get set in wp-config.php as:

```php
define('WP_MAIL_FROM', 'Person &amp; Person Company');
```
